name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm-cache

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-15, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - if: startsWith(matrix.os, 'windows')
        uses: microsoft/setup-msbuild@v2
      - if: startsWith(matrix.os, 'windows')
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - uses: extractions/setup-just@v2
      - if: startsWith(matrix.os, 'windows')
        run: pip install meson ninja
      - name: Cache CMake builds
        uses: actions/cache@v4
        with:
          path: |
            ~/.cmake
            build
          key: ${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-cmake-
      - if: startsWith(matrix.os, 'macos')
        name: Install macos dependencies
        run: brew install pkg-config glfw meson
      - if: startsWith(matrix.os, 'ubuntu')
        name: Install linux dependencies
        run: sudo apt-get update && sudo apt-get install -y pkg-config libglfw3-dev meson ninja-build libdbus-1-dev libxkbcommon-dev libfreetype-dev libtbb-dev libwayland-dev libglvnd-dev
      - name: Trust git repo
        run: git config --global --add safe.directory '*'
      - if: ${{ !startsWith(matrix.os, 'windows') }}
        name: Library
        run: just library
      - name: Profiler GUI
        run: just build profiler
      - name: Update utility
        run: just build update
      - name: Capture utility
        run: just build capture
      - name: Csvexport utility
        run: just build csvexport
      - name: Import utilities
        run: just build import
      - if: ${{ startsWith(matrix.os, 'ubuntu') }}
        name: Test compilation with different flags
        run: just compile_test
      - name: Find Artifacts
        id: find_artifacts
        run: just copy_artifacts
      - if: ${{ !startsWith(matrix.os, 'windows') }}
        name: Symlink
        run: just symlink
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: bin
