name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm-cache

jobs:
  build:
    strategy:
      matrix:
        include:
          - runningSystem: windows-latest
            testCompilation: false
            webBuild: false
          - runningSystem: ubuntu-latest
            testCompilation: true
            webBuild: false
          - runningSystem: ubuntu-latest
            testCompilation: false
            webBuild: true
          - runningSystem: macos-15
            testCompilation: false
            webBuild: false
    uses: ./.github/workflows/build_base.yml
    with:
      runningSystem: ${{ matrix.runningSystem }}
      testCompilation: ${{ matrix.testCompilation }}
      webBuild: false
  build_web:
    uses: ./.github/workflows/emscripten.yml
    with:
      deploy: false
  build_linux_arch:
    uses: ./.github/workflows/linux.yml
