name: emscripten

on:
  push:
    tags:
      - ".*"
  workflow_dispatch:
    inputs:
      deploy:
        description: "Deploy artifacts"
        required: false
        default: false
        type: boolean
  workflow_call:
    inputs:
      deploy:
        description: "Deploy artifacts"
        required: false
        default: false
        type: boolean

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm-cache

jobs:
  build:
    uses: ./.github/workflows/build_base.yml
    with:
      runningSystem: ubuntu-latest
      testCompilation: false
      webBuild: true
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/') || inputs.deploy == true
    steps:
      - uses: actions/download-artifact@v4
      - uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.USERNAME }}
          server: ${{ secrets.SERVER }}
          port: ${{ secrets.PORT }}
          ssh_private_key: ${{ secrets.PRIVATE_KEY }}
          local_path: "./emscripten/*"
          remote_path: ${{ secrets.REMOTE_PATH }}
          sftp_only: true
