name: emscripten

on:
  push:
    tags:
      - ".*"
  workflow_dispatch:
    inputs:
      deploy:
        description: "Deploy artifacts"
        required: false
        default: false
        type: boolean
  workflow_call:
    inputs:
      deploy:
        description: "Deploy artifacts"
        required: false
        default: false
        type: boolean

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm-cache

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y pkg-config libglfw3-dev meson ninja-build libdbus-1-dev libxkbcommon-dev libfreetype-dev libtbb-dev libwayland-dev libglvnd-dev zstd
      - name: Setup emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 4.0.10
      - uses: extractions/setup-just@v2
      - name: Trust git repo
        run: git config --global --add safe.directory '*'
      - uses: actions/checkout@v4
      - name: Profiler GUI
        run: just web_build ${{ github.sha }}
      - name: Compress artifacts
        run: just web_compress_artifacts
      - name: Find Artifacts
        id: find_artifacts
        run: just web_copy_artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: emscripten
          path: bin
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/') || inputs.deploy == true
    steps:
      - uses: actions/download-artifact@v4
      - uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.USERNAME }}
          server: ${{ secrets.SERVER }}
          port: ${{ secrets.PORT }}
          ssh_private_key: ${{ secrets.PRIVATE_KEY }}
          local_path: "./emscripten/*"
          remote_path: ${{ secrets.REMOTE_PATH }}
          sftp_only: true
