name: linux

on:
  workflow_call:

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm-cache

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - name: Install dependencies
        run: pacman -Syu --noconfirm && pacman -S --noconfirm --needed freetype2 debuginfod wayland dbus libxkbcommon libglvnd meson cmake git wayland-protocols nodejs
      - name: Trust git repo
        run: git config --global --add safe.directory '*'
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - name: Cache CPM packages
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/cpm-cache
            ~/.cache/CPM
          key: arch-linux-cpm-${{ hashFiles('**/vendor.cmake', '**/CMakeLists.txt') }}
          restore-keys: |
            arch-linux-cpm-
      - name: Library
        run: just library
      - name: Profiler GUI
        run: just build profiler
      - name: Update utility
        run: just build update
      - name: Capture utility
        run: just build capture
      - name: Csvexport utility
        run: just build csvexport
      - name: Import utilities
        run: just build import
      - name: Test compilation with different flags
        run: just compile_tests
      - name: Find Artifacts
        id: find_artifacts
        run: just copy_artifacts
      - name: Strip binaries
        run: just strip_binary
      - uses: actions/upload-artifact@v4
        with:
          name: arch-linux
          path: bin
